name: CVE scan

on:
  #  push:
  #  pull_request:
  #  Temporarily disabled due to failures, will be integrated with cve-bin-tool-action
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cve_scan:
    name: CVE scan on dependencies
    # runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}
    runs-on: 'ubuntu-latest'
    timeout-minutes: 60
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      - name: Get date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      - name: Get cached database
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: cache
          key: Linux-cve-bin-tool-${{ steps.get-date.outputs.date }}
      - name: Install dependencies and cve-bin-tool
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
          python -m pip install --upgrade pytest
          pip install . -r doc/requirements.txt
          [[ -e cache ]] && mkdir -p .cache && mv -f cache .cache/cve-bin-tool
          sleep 5
      - name: Test to check for CVEs for Python requirements and HTML report dependencies
        run: |
          pytest test/test_requirements.py
