name: Validate mismatch_relations.yml

permissions: read-all

on:
  push:
    paths:
      - data/**/mismatch_relations.yml
  workflow_dispatch:

jobs:
  validate-yml:
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pyyaml
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Get Modified mismatch_relations.yml Files
        id: get-modified-files
        run: |
          git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} | grep '^mismatch_data/.*/mismatch_relations.yml$' > modified_files.txt

      - name: Validate Modified YAML Files
        if: success()
        run: |
          if [ -s modified_files.txt ]; then
            python .github/workflows/yaml_rules.py $(cat modified_files.txt)
          else
            echo "No modified mismatch_relations.yml files to validate."
          fi
